---
scanInfo:
  resultPath: "/Users/ricky/Krew/OSA/CLI 테스트/ngrinder-test/ngrinder-gradle/work/1"
  revisionId: 1
  executed: "2022-01-19T15:32:33.931331"
  status: "ANALYZED"
projectTitle: "olive-cli-test"
userConfig:
  openSource: false
  excludePaths: []
  gradleBuildVariant: ""
  excludeGradle: []
version: "v1"
cliInfo:
  apiToken: "1mPgr3muyD"
  sourcePath: "/Users/ricky/Krew/OSA/CLI 테스트/ngrinder-test/ngrinder-gradle"
  basePath: "/Users/ricky/Krew/OSA/CLI 테스트/ngrinder-test/ngrinder-gradle/work"
  server: "https://olive-api-dev.devel.kakao.com"
